//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorSplasher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorSplasher.Resource.fr", typeof(Resource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Révisé en bleu.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conflit (s) détecté (s).
        /// </summary>
        public static string ClashDetected {
            get {
                return ResourceManager.GetString("ClashDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne sommes pas en mesure de créer la vue 3D..
        /// </summary>
        public static string Error_3DView {
            get {
                return ResourceManager.GetString("Error_3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez être dans un environnement de projet pour utiliser Color Splasher mais vous êtes actuellement dans un environnement familial. Veuillez ouvrir un projet et réessayer..
        /// </summary>
        public static string Error_FamilyProject {
            get {
                return ResourceManager.GetString("Error_FamilyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier lié est enregistré mais nous ne pouvons pas le lier. ..
        /// </summary>
        public static string Error_LinkedFileNotLinked {
            get {
                return ResourceManager.GetString("Error_LinkedFileNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne pouvons pas enregistrer le fichier lié. Veuillez réimporter le rapport et vérifier que vous avez accès au chemin spécifié. Si l&apos;erreur persiste, ..
        /// </summary>
        public static string Error_LinkedFileNotSaved {
            get {
                return ResourceManager.GetString("Error_LinkedFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun affrontement n&apos;a été lu dans le rapport Naviswork. Voici les raisons possibles pour lesquelles nous ne pouvons pas importer les conflits:
        ///
        ///   • Vous avez sélectionné le mauvais fichier. Le rapport doit être un fichier .xml
        ///   • Le rapport ne contient pas d&apos;affrontements
        ///   • Des champs manquent dans le rapport de conflit
        ///
        ///.
        /// </summary>
        public static string Error_NoClashRead {
            get {
                return ResourceManager.GetString("Error_NoClashRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne pouvons pas lire le fichier de famille de la sphère de conflit (.rfa). Essaye ça:
        ///
        ///    1. Fermez Revit et réessayez
        ///    2. Réinstallez le plugin
        ///
        ///.
        /// </summary>
        public static string Error_RevitFileNotAccessible {
            get {
                return ResourceManager.GetString("Error_RevitFileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne pouvons pas lire le fichier lié au modèle Revit (Coordination Report.rte). Essaye ça:
        ///
        ///    1. Fermez Revit et réessayez
        ///    2. Réinstallez le plugin
        ///
        ///.
        /// </summary>
        public static string Error_RevitTemplateFileNotAccessible {
            get {
                return ResourceManager.GetString("Error_RevitTemplateFileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet doit être enregistré avant d&apos;utiliser cet outil.
        /// </summary>
        public static string Error_SaveYourFile {
            get {
                return ResourceManager.GetString("Error_SaveYourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne sommes pas en mesure de créer la nomenclature. Veuillez le faire manuellement et contacter le support..
        /// </summary>
        public static string Error_Schedule {
            get {
                return ResourceManager.GetString("Error_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle? Comment obtenez-vous cela? Il s&apos;agit d&apos;une erreur inconnue. ..
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fichier (s) sélectionné (s),.
        /// </summary>
        public static string FileSelected {
            get {
                return ResourceManager.GetString("FileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer.
        /// </summary>
        public static string FormBtn_ApplyColorSet {
            get {
                return ResourceManager.GetString("FormBtn_ApplyColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string FormBtn_ClearSet {
            get {
                return ResourceManager.GetString("FormBtn_ClearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger le schéma.
        /// </summary>
        public static string FormBtn_LoadSchema {
            get {
                return ResourceManager.GetString("FormBtn_LoadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc-en-ciel.
        /// </summary>
        public static string FormBtn_Rainbow {
            get {
                return ResourceManager.GetString("FormBtn_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchir.
        /// </summary>
        public static string FormBtn_Refresh {
            get {
                return ResourceManager.GetString("FormBtn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer le schéma.
        /// </summary>
        public static string FormBtn_SaveSchema {
            get {
                return ResourceManager.GetString("FormBtn_SaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie (maintenez la touche Ctrl enfoncée pour plusieurs sélections).
        /// </summary>
        public static string FormTitle_CategoryHoldCtrlForMultipleSelections {
            get {
                return ResourceManager.GetString("FormTitle_CategoryHoldCtrlForMultipleSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres.
        /// </summary>
        public static string FormTitle_Filters {
            get {
                return ResourceManager.GetString("FormTitle_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string FormTitle_Parameters {
            get {
                return ResourceManager.GetString("FormTitle_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs.
        /// </summary>
        public static string FormTitle_Values {
            get {
                return ResourceManager.GetString("FormTitle_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer la configuration de couleur.
        /// </summary>
        public static string FormToolTipBtn_ApplyColorSet {
            get {
                return ResourceManager.GetString("FormToolTipBtn_ApplyColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser tous les remplacements.
        /// </summary>
        public static string FormToolTipBtn_ClearSet {
            get {
                return ResourceManager.GetString("FormToolTipBtn_ClearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger le fichier csch.
        /// </summary>
        public static string FormToolTipBtn_LoadSchema {
            get {
                return ResourceManager.GetString("FormToolTipBtn_LoadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un morphing de jeu de couleurs du début à la fin.
        /// </summary>
        public static string FormToolTipBtn_Rainbow {
            get {
                return ResourceManager.GetString("FormToolTipBtn_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer un jeu de couleurs aléatoire.
        /// </summary>
        public static string FormToolTipBtn_Refresh {
            get {
                return ResourceManager.GetString("FormToolTipBtn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer le fichier csch.
        /// </summary>
        public static string FormToolTipBtn_SaveSchema {
            get {
                return ResourceManager.GetString("FormToolTipBtn_SaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approuvé vert.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de l&apos;importation. Veuillez réessayer....
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  clash spheres générées !.
        /// </summary>
        public static string ImportSuceed {
            get {
                return ResourceManager.GetString("ImportSuceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lier le fichier hôte au nouveau fichier.
        /// </summary>
        public static string LinkOfFileNewFile {
            get {
                return ResourceManager.GetString("LinkOfFileNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez d&apos;abord sélectionner le paramètre.
        /// </summary>
        public static string MsgBox_PleaseSelectParameterFirst {
            get {
                return ResourceManager.GetString("MsgBox_PleaseSelectParameterFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez un paramètre.
        /// </summary>
        public static string MsgBox_SelectAParameter {
            get {
                return ResourceManager.GetString("MsgBox_SelectAParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement.
        /// </summary>
        public static string MsgBox_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez avoir détecté au moins 1 conflit pour importer le rapport.
        /// </summary>
        public static string NoClashDetected {
            get {
                return ResourceManager.GetString("NoClashDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange-Actif.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouge-Nouveau.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez le dossier dans lequel vous souhaitez enregistrer le fichier lié.
        /// </summary>
        public static string SelectYourFolder {
            get {
                return ResourceManager.GetString("SelectYourFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion au serveur impossible.
        /// </summary>
        public static string ToolBox_CannotConnectToServeur {
            get {
                return ResourceManager.GetString("ToolBox_CannotConnectToServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string ToolBox_Exit {
            get {
                return ResourceManager.GetString("ToolBox_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string ToolBox_Help {
            get {
                return ResourceManager.GetString("ToolBox_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle version disponible.
        /// </summary>
        public static string ToolBox_NewversionAvailable {
            get {
                return ResourceManager.GetString("ToolBox_NewversionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version à jour.
        /// </summary>
        public static string ToolBox_NoNewVersionAvailable {
            get {
                return ResourceManager.GetString("ToolBox_NoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ToolBox_Support {
            get {
                return ResourceManager.GetString("ToolBox_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.2.0.1.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résolu en jaune.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
