//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorSplasher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorSplasher.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue-Reviewed.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  clash(es) detected.
        /// </summary>
        public static string ClashDetected {
            get {
                return ResourceManager.GetString("ClashDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to create the 3D view. .
        /// </summary>
        public static string Error_3DView {
            get {
                return ResourceManager.GetString("Error_3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in a project environement to use the Color Splasher but you are currently in a family environment. Please open a project and try again..
        /// </summary>
        public static string Error_FamilyProject {
            get {
                return ResourceManager.GetString("Error_FamilyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file is saved but we are not able to link it. .
        /// </summary>
        public static string Error_LinkedFileNotLinked {
            get {
                return ResourceManager.GetString("Error_LinkedFileNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to save the linked file. Please try to import the report again and check you have access to the specified path. If you still have the error .
        /// </summary>
        public static string Error_LinkedFileNotSaved {
            get {
                return ResourceManager.GetString("Error_LinkedFileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clash was read in the Naviswork report. Here are possible reasons why we are not able to import the clashes:
        ///
        ///  • You selected the wrong file. The report must be a .xml file
        ///  • The report does not contain clashes
        ///  • Fields are missing in the clash report
        ///
        ///.
        /// </summary>
        public static string Error_NoClashRead {
            get {
                return ResourceManager.GetString("Error_NoClashRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to read the clash sphere family file (.rfa). Try this:
        ///
        ///   1. Close Revit and try again
        ///   2. Reinstall the plugin
        ///
        ///.
        /// </summary>
        public static string Error_RevitFileNotAccessible {
            get {
                return ResourceManager.GetString("Error_RevitFileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to read the revit template linked file (Coordination Report.rte). Try this:
        ///
        ///   1. Close Revit and try again
        ///   2. Reinstall the plugin
        ///
        ///.
        /// </summary>
        public static string Error_RevitTemplateFileNotAccessible {
            get {
                return ResourceManager.GetString("Error_RevitTemplateFileNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project must be saved before using this tool.
        /// </summary>
        public static string Error_SaveYourFile {
            get {
                return ResourceManager.GetString("Error_SaveYourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not able to create the schedule. Please do it manually and contact the support..
        /// </summary>
        public static string Error_Schedule {
            get {
                return ResourceManager.GetString("Error_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What? How do you get this? This is an unknown error. .
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  file(s) selected, .
        /// </summary>
        public static string FileSelected {
            get {
                return ResourceManager.GetString("FileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply color set.
        /// </summary>
        public static string FormBtn_ApplyColorSet {
            get {
                return ResourceManager.GetString("FormBtn_ApplyColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear set.
        /// </summary>
        public static string FormBtn_ClearSet {
            get {
                return ResourceManager.GetString("FormBtn_ClearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load schema.
        /// </summary>
        public static string FormBtn_LoadSchema {
            get {
                return ResourceManager.GetString("FormBtn_LoadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        public static string FormBtn_Rainbow {
            get {
                return ResourceManager.GetString("FormBtn_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string FormBtn_Refresh {
            get {
                return ResourceManager.GetString("FormBtn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save schema.
        /// </summary>
        public static string FormBtn_SaveSchema {
            get {
                return ResourceManager.GetString("FormBtn_SaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category (Hold Ctrl for multiple selections).
        /// </summary>
        public static string FormTitle_CategoryHoldCtrlForMultipleSelections {
            get {
                return ResourceManager.GetString("FormTitle_CategoryHoldCtrlForMultipleSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FormTitle_Filters {
            get {
                return ResourceManager.GetString("FormTitle_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string FormTitle_Parameters {
            get {
                return ResourceManager.GetString("FormTitle_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string FormTitle_Values {
            get {
                return ResourceManager.GetString("FormTitle_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash color.
        /// </summary>
        public static string FormToolTipBtn_ApplyColorSet {
            get {
                return ResourceManager.GetString("FormToolTipBtn_ApplyColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all overrides.
        /// </summary>
        public static string FormToolTipBtn_ClearSet {
            get {
                return ResourceManager.GetString("FormToolTipBtn_ClearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load csch file.
        /// </summary>
        public static string FormToolTipBtn_LoadSchema {
            get {
                return ResourceManager.GetString("FormToolTipBtn_LoadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a color set morphing from the start to end color.
        /// </summary>
        public static string FormToolTipBtn_Rainbow {
            get {
                return ResourceManager.GetString("FormToolTipBtn_Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a random color set.
        /// </summary>
        public static string FormToolTipBtn_Refresh {
            get {
                return ResourceManager.GetString("FormToolTipBtn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save csch file.
        /// </summary>
        public static string FormToolTipBtn_SaveSchema {
            get {
                return ResourceManager.GetString("FormToolTipBtn_SaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green-Approved.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed. Please try again....
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  clash spheres generated!.
        /// </summary>
        public static string ImportSuceed {
            get {
                return ResourceManager.GetString("ImportSuceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link the host file with the new file.
        /// </summary>
        public static string LinkOfFileNewFile {
            get {
                return ResourceManager.GetString("LinkOfFileNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select parameter first.
        /// </summary>
        public static string MsgBox_PleaseSelectParameterFirst {
            get {
                return ResourceManager.GetString("MsgBox_PleaseSelectParameterFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a parameter.
        /// </summary>
        public static string MsgBox_SelectAParameter {
            get {
                return ResourceManager.GetString("MsgBox_SelectAParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgBox_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have minimum 1 clash detected to import the report.
        /// </summary>
        public static string NoClashDetected {
            get {
                return ResourceManager.GetString("NoClashDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange-Active.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red-New.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where you want to save the linked file.
        /// </summary>
        public static string SelectYourFolder {
            get {
                return ResourceManager.GetString("SelectYourFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to server.
        /// </summary>
        public static string ToolBox_CannotConnectToServeur {
            get {
                return ResourceManager.GetString("ToolBox_CannotConnectToServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ToolBox_Exit {
            get {
                return ResourceManager.GetString("ToolBox_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ToolBox_Help {
            get {
                return ResourceManager.GetString("ToolBox_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string ToolBox_NewversionAvailable {
            get {
                return ResourceManager.GetString("ToolBox_NewversionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated version.
        /// </summary>
        public static string ToolBox_NoNewVersionAvailable {
            get {
                return ResourceManager.GetString("ToolBox_NoNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ToolBox_Support {
            get {
                return ResourceManager.GetString("ToolBox_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.2.0.1.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow-Resolved.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
